
* TFBD generated externals
*     (c) PHC 1992,93


         EXT   L033477
         EXT   L0313BE
         EXT   L0338DC
         EXT   L0337CC
         EXT   L05565D
         EXT   L032F1F
         EXT   L033095
         EXT   L032FA4
         EXT   L0337F3
         EXT   L033467
         EXT   L033930
         EXT   L0338B0
         EXT   L033888
         EXT   L0555A3
         EXT   L0339B7
         EXT   L055661
         EXT   L0555BB
         EXT   L0556D2
         EXT   L0555AB
