*
* Lode Runner
* (c) 1983, Broderbund Software
* (s) 2014, Brutal Deluxe Software
*

*-----------------------------------
* SOUND BANK 1
*-----------------------------------

sndBARRE	ent
	putbin	snd/barre.snd
sndCREUSE	ent
	putbin	snd/creuse.snd
sndESCALIER	ent
	putbin	snd/escalier.snd
sndMARCHE	ent
	putbin	snd/marche.snd
sndNOMORECHEST	ent
	putbin	snd/nomorechest.snd
sndTOMBE	ent
	putbin	snd/tombe.snd
sndTRESOR	ent
	putbin	snd/tresor.snd
sndTROU	ent
	putbin	snd/trou.snd
sndYOUWIN	ent
	putbin	snd/youwin.snd
	