
* TFBD generated externals
*     (c) PHC 1992,93


            EXT   L013048
            EXT   L012E77
            EXT   L0133D4
            EXT   L031DDC
            EXT   L031DDA
            EXT   L013333
            EXT   L050256
            EXT   L013F1E
            EXT   L01493B
            EXT   L014C78
            EXT   L013A1F
            EXT   L01508C
            EXT   L033CC5
            EXT   L033CDD
            EXT   L037E33
            EXT   L033CE4
            EXT   L033CED
            EXT   L033CF9

