
* TFBD generated externals
*     (c) PHC 1992,93


         EXT   L1A0E02
         EXT   L1A0F9E
         EXT   L1A0E95
         EXT   L070000
         EXT   L020151
         EXT   L02014F
         EXT   L02014D
         EXT   L02014B
         EXT   L1A130B
         EXT   L020091
         EXT   L020093
         EXT   L02008B
         EXT   L020089
         EXT   L02008F
         EXT   L02008D
         EXT   L0F11B0
         EXT   L060318
         EXT   L0705E1
         EXT   L04039E
         EXT   L0200A2
         EXT   L0200A0
         EXT   L020116
         EXT   L020118
         EXT   L180000
         EXT   L1D0395
         EXT   L1302A9
         EXT   L1B002E
         EXT   L120231
         EXT   L1F006F
         EXT   L12019F
         EXT   L020097
         EXT   L020095
         EXT   L032054
