
* TFBD generated externals
*     (c) PHC 1992,93


         EXT   L0201E7
         EXT   L1A0EFF
         EXT   L1A0DAA
         EXT   L1A0F19
         EXT   L1A0F9E
         EXT   L0C0000
         EXT   L1A109A
         EXT   L1A10DF
         EXT   L02016B
         EXT   L02016D
         EXT   L020165
         EXT   L020163
         EXT   L09007C
         EXT   L0201B7
         EXT   L0201B9
         EXT   L0F144E
         EXT   L0201B3
         EXT   L0201B1
         EXT   L0201AF
         EXT   L0201B5
         EXT   L0201BF
         EXT   L0C0023
         EXT   L1C0473
         EXT   L1C04C6
         EXT   L1C04EC
         EXT   L1C051C
         EXT   L0201C3
         EXT   L0201C1
         EXT   L0201C5
         EXT   L0201C7
         EXT   L0201BD
         EXT   L032B33
         EXT   L032B24
