
* TFBD generated externals
*     (c) PHC 1992,93


         EXT   L0B0004
         EXT   L0D0000
         EXT   L0E003C
         EXT   L0B0002
         EXT   L0C002A
         EXT   L0C0028
         EXT   L0C002C
         EXT   L0E0012
         EXT   L0E0020
         EXT   L0E002E
         EXT   L0402A6
         EXT   L040463
         EXT   L040619
         EXT   L023C7E
         EXT   L024DE0
         EXT   L0C2CEA
         EXT   L0C2D57
         EXT   L0C2D55
         EXT   L0C2D45
         EXT   L0C2CDC
         EXT   L0C2CDA
         EXT   L0B0014
         EXT   L0B0012
         EXT   L0B0018
         EXT   L0B0016
         EXT   L0B000A
         EXT   L0B0008
         EXT   L0B0006
         EXT   L0B000E
         EXT   L0B0010
         EXT   L0B0000
         EXT   L0B000C
         EXT   L0B0088
         EXT   L0B0068
         EXT   L0B0082
         EXT   L0B011D
         EXT   L0C0000
         EXT   L0C0020
         EXT   L0C1220
         EXT   L0C1124
         EXT   L0C2D08
         EXT   L0C2D46
