
* Expansion linker file

         DSK   YOURTOUR
         TYP   S16

* Assemble files

         ASM   MAIN.S
         KND   $0000
         SNA   MAIN

         ASM   ONE.S
         KND   $0000
         SNA   ONE

         ASM   TWO.S
         KND   $0000
         SNA   TWO

         ASM   THREE.S
         KND   $0000
         SNA   THREE

         ASM   FOUR.S
         KND   $0000
         SNA   FOUR

         ASM   FIVE.S
         KND   $0000
         SNA   FIVE

         ASM   SIX.S
         KND   $0000
         SNA   SIX

         ASM   CTRICKS.S
         KND   $8000
         SNA   CTRICKS

         ASM   LTRICKS.S
         KND   $8000
         SNA   LTRICKS

         ASM   INIT.S
         KND   $8000
         SNA   INIT

         ASM   GLOBALS.S
         KND   $4001
         SNA   GLOBALS

         ASM   ARRAYS.S
         KND   $4001
         SNA   ARRAYS

         ASM   DIRECT.S
         KND   $0012
         SNA   DIRECT

         ASM   JUMPTABLE.S
         KND   $0002
         SNA   JUMPTABLE


* END
