*
* Archiver GS
*
* (c) 1992, Apple Computer, Inc.
* (s) 2023, Antoine Vignau
*

	mx	%00
	rel
	lst	off

*-----------------------------------

            EXT   L0612EF
            EXT   L050020
            EXT   L0612ED
            EXT   L050022
            EXT   L050024
            EXT   L074A31
            EXT   L07494A
            EXT   L074538
            EXT   L0743FE
            EXT   L070000
            EXT   L050425
            EXT   L061242
            EXT   L06124A
            EXT   L07001D
            EXT   L0612BF
            EXT   L0612BD
            EXT   L06000C
            EXT   L060002
            EXT   L06000A
            EXT   L040023
            EXT   L04002B
            EXT   L040025
            EXT   L040027
            EXT   L040029
            EXT   L041DEA
            EXT   L040026
            EXT   L060006
            EXT   L060124
            EXT   L0514C3
            EXT   L0514C4
            EXT   L0514E1
            EXT   L0514D1
            EXT   L0514D3
            EXT   L051537
            EXT   L050000
            EXT   L0514C7
            EXT   L05004E
            EXT   L05009E
            EXT   L05002A
            EXT   L0514B5
            EXT   L0514B8
            EXT   L0514BA
            EXT   L0514BC
            EXT   L0514BF
            EXT   L0514C1
            EXT   L0514C5
            EXT   L05152F
            EXT   L051538
            EXT   L0612F3
            EXT   L0612F1
            EXT   L0612E9
            EXT   L060000
            EXT   L0612E1
            EXT   L0612DF
            EXT   L0612F5
            EXT   L0612E5
            EXT   L0612E7
            EXT   L0612E3
            EXT   L06006E
            EXT   L060436
            EXT   L0600DC
            EXT   L0600D8
            EXT   L0600DA
            EXT   L060004
            EXT   L0600CE
            EXT   L06125A
            EXT   L06127C
            EXT   L061296
            EXT   L061297
            EXT   L060020
            EXT   L061206
            EXT   L06120E
            EXT   L0612D1
            EXT   L0612D3
            EXT   L0612C5
            EXT   L0612C7
            EXT   L0612D5
            EXT   L0612D7
            EXT   L0612C1
            EXT   L0612C3
            EXT   L0612DB
            EXT   L0612DD
            EXT   L0612EB

