
* TFBD generated externals
*     (c) PHC 1992,93


         EXT   L0196BB
         EXT   L0196BD
         EXT   L019EE0
         EXT   L019976
         EXT   L019978
         EXT   L0196C7
         EXT   L0196C5
         EXT   L019E74
         EXT   L019A14
         EXT   L0199F4
         EXT   L01493B
         EXT   L0149AE
         EXT   L0182D0
         EXT   L014903
         EXT   L0181CE
         EXT   L0196C1
         EXT   L01A2C4
