
* TFBD generated externals
*     (c) PHC 1992,93


         EXT   L0196BB
         EXT   L018744
         EXT   L01A458
         EXT   L019EE0
         EXT   L019976
         EXT   L019978
         EXT   L0196C9
         EXT   L0196C7
         EXT   L0196C5
         EXT   L019E74
         EXT   L019998
         EXT   L01999A
         EXT   L0199F4
         EXT   L0149AE
         EXT   L01046F
         EXT   L010472
         EXT   L019825
         EXT   L01997C
         EXT   L019683
         EXT   L019681
         EXT   L01855E
         EXT   L0183EE
         EXT   L0118C4
         EXT   L01436D
         EXT   L01194B
