*
* Shufflepuck Cafe
* make
*
* (c) 2025, Brutal Deluxe Software
*

            DSK   SHUFFLE
            TYP   $B3
            
            ASM   SEG01.S
            KND   $0000
            ASM   SEG02.S
            KND   $4401        ; 4401
            ASM   SEG03.S
            KND   $4401        ; 4401
            ASM   SEG04.S
            KND   $0000
            ASM   SEG05.S
            KND   $0000
            ASM   SEG06.S
            KND   $0000
            ASM   SEG07.S
            KND   $0000
            ASM   SEG08.S
            KND   $0000
            ASM   SEG09.S
            KND   $0000
            ASM   SEG0A.S
            KND   $0000
            ASM   SEG0B.S
            KND   $0000
            ASM   SEG0C.S
            KND   $0000
            ASM   SEG0D.S
            KND   $0000
            ASM   SEG0E.S
            KND   $0000
            ASM   SEG0F.S
            KND   $0000

            ASM   SEG10.S
            KND   $0000
            ASM   SEG11.S
            KND   $0000
            ASM   SEG12.S
            KND   $0000
            ASM   SEG13.S
            KND   $0000
            ASM   SEG14.S
            KND   $0000
            ASM   SEG15.S
            KND   $0000
            ASM   SEG16.S
            KND   $0000
            ASM   SEG17.S
            KND   $0000
            ASM   SEG18.S
            KND   $0000
            ASM   SEG19.S
            KND   $0000
            ASM   SEG1A.S
            KND   $0000
            ASM   SEG1B.S
            KND   $0000
            ASM   SEG1C.S
            KND   $0000
            ASM   SEG1D.S
            KND   $0000
            ASM   SEG1E.S
            KND   $0000
            ASM   SEG1F.S
            KND   $0000

            ASM   SEG20.S
            KND   $0000
            ASM   SEG21.S
            KND   $0000
            ASM   SEG22.S
            KND   $0000
            ASM   SEG23.S
            KND   $0000
            ASM   SEG24.S
            KND   $0000
            ASM   SEG25.S
            KND   $0000
            ASM   SEG26.S
            KND   $0000
            ASM   SEG27.S
            KND   $0000
