
* TFBD generated externals
*     (c) PHC 1992,93


	ext	doRECTANGLE
	ext	doTHERMOMETER
         EXT   L030057
         EXT   L0310E1
         EXT   L03447D
         EXT   L03455D
         EXT   L03463D
         EXT   L03471D
         EXT   L030853
         EXT   L030B5F
         EXT   L030E51
         EXT   L03143D
         EXT   L03171C
         EXT   L0322D6
         EXT   L0327DA
         EXT   L032B88
         EXT   L032D53
         EXT   L032F4A
         EXT   L0334C2
         EXT   L0337FF
         EXT   L033A79
         EXT   L033CF3
         EXT   L030524
